# Generated by Django 3.2.17 on 2024-12-18 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('delai', models.CharField(blank=True, max_length=100)),
                ('ordre', models.IntegerField()),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in-progress', 'En cours'), ('waiting', 'En attente'), ('done', 'Terminé')], default='todo', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='CentreDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Centre DI',
                'verbose_name_plural': 'Centres DI',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GMR',
                'verbose_name_plural': 'GMR',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GroupeInterlocuteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Groupe d'interlocuteurs",
                'verbose_name_plural': "Groupes d'interlocuteurs",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProcessusEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre_global', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('selectionne', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in-progress', 'En cours'), ('waiting', 'En attente'), ('done', 'Terminé')], default='todo', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Étape du processus',
                'verbose_name_plural': 'Étapes du processus',
                'ordering': ['ordre_global', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('selectionne', models.BooleanField(default=False)),
                ('centre_di', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centredi', verbose_name='Centre DI')),
                ('gmr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gmr', verbose_name='GMR')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('is_di', models.BooleanField(default=False, verbose_name='Est un rôle DI')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de rôle',
                'verbose_name_plural': 'Types de rôles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in-progress', 'En cours'), ('waiting', 'En attente'), ('done', 'Terminé')], default='todo', max_length=20, verbose_name='Statut')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.action', verbose_name='Action parente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subtasks', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Sous-tâche',
                'verbose_name_plural': 'Sous-tâches',
                'db_table': 'core_subtask',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interlocuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interlocuteurs', to='core.groupeinterlocuteurs')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interlocuteurs', to='core.projet')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interlocuteurs', to='core.roletype')),
            ],
            options={
                'verbose_name': 'Interlocuteur',
                'verbose_name_plural': 'Interlocuteurs',
                'ordering': ['groupe__ordre', 'role__ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='groupeinterlocuteurs',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_interlocuteurs', to='core.projet'),
        ),
        migrations.AddField(
            model_name='action',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.processusetape'),
        ),
        migrations.AddField(
            model_name='action',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.projet'),
        ),
        migrations.CreateModel(
            name='ProcessusSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_selectionne', models.BooleanField(default=False)),
                ('date_selection', models.DateTimeField(auto_now=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processusetape')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projet')),
            ],
            options={
                'unique_together': {('projet', 'etape')},
            },
        ),
    ]
