# Generated by Django 3.2.17 on 2024-12-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241218_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='for_planning',
            field=models.BooleanField(default=False),
        ),
    ]
