# Generated by Django 3.2.17 on 2024-12-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subtask_for_planning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='for_planning',
            new_name='in_planning',
        ),
    ]
